version: "3.8"
services:
  bot:
    container_name: "Discord_Bot_Application"
    build: .
    command: yarn start
    tty: true
    depends_on:
      - db
    environment:
      NODE_ENV: production
    volumes:
      - ./logs:/usr/app/logs/
      - ./config:/usr/app/config/
  db:
    container_name: "Discord_Bot_Database"
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgresql
      - POSTGRES_PASSWORD=postgresql
      - POSTGRES_DB=Bot
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
