version: "3.8"
services:
  bot:
    container_name: "Discord Bot Application"
    build: .
    command: yarn start
    tty: true
    depends_on:
      - db
    environment:
      NODE_ENV: production
    links:
      - db
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgresql
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=Bot
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
