#!/usr/bin/env bash
. "$(dirname -- "$0")/_/husky.sh"

for file in $(git diff --cached --name-only | grep -E '.[tj]s$'); do
  if ! git show ":$file" | yarn lint --stdin --stdin-filename "$file"; then
    echo "ESLint failed on staged file '$file'. Please check your code and try again."
    exit 1
  fi
done
