name: Typescript Deployment.

on:
  push:
    branches: [ js ]
  pull_request:
    branches: [ js ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x, 17.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: ./.github/workflow/setup.yml
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn run test
    - run: yarn run build

  lint:
    name: Analyse Code
    runs-on: ubuntu-latest
    # if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
      - name: Setup NodeJS Environment
        uses: actions/setup-node@v2
        with:
          node-version: 17
      - name: Execute ESlint
        run: |
          yarn lint

# TODO: Deployment/Publish Job
