name: On Pull, Merge to Master

on:
  push:
    branch:
      - main

jobs:
  prepare:
    runs-on: ubuntu-20.04

    env:
      NODE_ENV: development

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19

      - name: Build and test.
        uses: actions/buildAndTest