name: Node.js Deployment.

on:
  push:
    branches: [ js ]
  pull_request:
    branches: [ js ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16, 17 ]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn --frozen-lockfile
      - run: yarn test
      - run: yarn lint
      - run: yarn build