name: On Pull, Merge to Master

on:
  workflow_dispatch:
  pull_request:

jobs:
  prepare:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: development

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19

      - run: yarn

  linting-test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - run: yarn lint

  testing-ts:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - run: yarn test

  testing-js:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - run: yarn build -p tsconfig.json
      - run: NODE_ENV='' yarn test
