name: On Pull, Merge to Master

on:
  workflow_dispatch:
  pull_request:

jobs:
  prepare:
    runs-on: ubuntu-latest

    env:
      NODE_ENV:development

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19

      - run: yarn
      - run: yarn build
      - run: yarn lint
      - run: yarn test
      - run: NODE_ENV='' yarn test
#  linting-test:
#    needs: build
#    runs-on: ubuntu-latest
#
#  testing-ts:
#    needs: build
#    runs-on: ubuntu-latest
#
#  testing-js:
#    needs: build
#    runs-on: ubuntu-latest
